### ISSUE TITLE
new sinaimg address

### ISSUE THREAD

**Issue by heyeshuang** [ivysrono/HeaderEditorRules#1]
he;llo, I saw a new sinaimg address which begins with "ws1" like this:

https://ws1.sinaimg.cn/large/62bfa70bly1g2futjhz2ij227i12aqt9.jpg

**Comment by ivysrono** [comment]
![test](https://ws1.sinaimg.cn/large/62bfa70bly1g2futjhz2ij227i12aqt9.jpg)

**Comment by ivysrono** [comment]
![wx](https://wx1.sinaimg.cn/large/62bfa70bly1g2futjhz2ij227i12aqt9.jpg)

**Comment by ivysrono** [comment]
一般认为，wx1234 有反盗链的问题，ws1234 没有。
你能给个测试页面不？

**Comment by heyeshuang** [comment]
https://wubaiqing.github.io/zaobao/2019/04/26.html
挺奇怪的，在文章中无法加载，直接在地址栏访问就可以了

**Comment by ivysrono** [comment]
![](https://ws1.sinaimg.cn/large/62bfa70bly1g2futjhz2ij227i12aqt9.jpg)
